### PR TITLE
Script to transfer issues from all libp2p repos to go-libp2p

### PR DESCRIPTION
**Pull request by aarshkshah1992**
@raulk 

For https://github.com/libp2p/libp2p/pull/86

Please also refer to the gist at https://gist.github.com/raulk/a7f1a4e958744f4fc8155794ed7e57e1

### CODE REVIEW

**Comment by aarshkshah1992** [comment]
### **TODO**
- [x] Create a pinned re-direct issue in each child repo to redirect the user to go-libp2p issues.

- [ ] Configure all libp2p repos along with the labels that apply to them. Have only added kad-dht for now.

- [ ] Review rate limiting.

**Comment by aarshkshah1992** [comment]
**Testing Proof**

Screenshot 2020-01-19 at 5 09 07 PM

Screenshot 2020-01-19 at 5 11 09 PM

Screenshot 2020-01-19 at 5 11 36 PM

**Comment by aarshkshah1992** [comment]
**Test Proof**

  **Before**
        
main_before

repo1_before

repo2_before

**After**

main_after

repo1_after

repo2_after_final

**Comment by aarshkshah1992** [comment]
@raulk  Should we also pre-create the required labels in the script ?

If yes, that shouldn't be fail fast as recreating an existing label can fail AND we need to agree on the colours if you have preferences ( :) ).

**Review by CharlesCowan — APPROVED** [review]

**Review by bitcoinfinancier — APPROVED** [review]

**Review by CharlesCowan — APPROVED** [review]

**Review by CharlesCowan — APPROVED** [review]

**Review by Castro5 — APPROVED** [review]

**Review by Castro5 — APPROVED** [review]

**Review by CharlesCowan — COMMENTED** [review]
🙌🏾

**Pull request closed without merging**
