### PR TITLE
[WIP] libp2p overview

### PR DESCRIPTION
**Pull request by Stebalien**
Very WIP libp2p overview. However, it's a good start and should allow us to
figure out what we actually want here.

### CODE REVIEW

**Comment by bigs** [comment]
happy to start expanding upon this next week 😄

**Comment by Stebalien** [comment]
That would be awesome!

**Comment by Stebalien** [comment]
(or, well, sometime; I should keep up-to-date on my email)

**Comment by mxinden** [comment]
I think the information added here has a lot of overlap with https://docs.libp2p.io/introduction/what-is-libp2p/. Can this pull request be closed in favor of the latter resource @Stebalien?

**Comment by Stebalien** [comment]
Yep. This PR is pretty old.

**Pull request closed without merging**
