### PR TITLE
REQUIREMENTS.md: Remove file

### PR DESCRIPTION
**Pull request by mxinden**
The document has not been touched for 2 years, is mostly outdated and has been partially replaced (see below). I am suggesting to remove the file entirely. Any objections?

- The `libp2p Modules Implementations` section is heavily outdated, with https://libp2p.io/implementations/ being a less outdated copy.

- The `Polish level` is in some sense covered by the [Maturity Levels](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md#maturity-levels) in the specs repo, as the latter not only covers the specification itself, but also the corresponding implementations.

### CODE REVIEW

**Review by raulk — COMMENTED** [review]
Do we have an updated matrix of module/implementations somewhere else? This is outdated, but I wonder if it's worth updating and modernising instead of removing (that part, at least).

**Comment by mxinden** [comment]
> Do we have an updated matrix of module/implementations somewhere else?

I would consider the [Implementations](https://libp2p.io/implementations/) and [Bundles](https://libp2p.io/bundles/) matrices a replacement. While a bit outdated, they are less outdated compared to the ones removed with this pull request.

@raulk does that sound reasonable?

**Comment by mxinden** [comment]
Friendly ping @raulk.

**Comment by mxinden** [comment]
Friendly ping @raulk.

**Review by raulk — APPROVED** [review]
> @raulk does that sound reasonable?

I think we absolutely need a updated matrix like this. I'm not sure which is more outdated, if the website or this one, but removing at least one of them doesn't seem too harmful.

**Pull request merged**
